# Generated by Django 4.1.1 on 2023-03-10 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_rank', models.IntegerField(blank=True, default=1, null=True)),
                ('curr_question', models.IntegerField(default=1)),
                ('questionIndexList', models.TextField(default='[-1]')),
                ('quesno', models.IntegerField(default=1)),
                ('mob_no', models.CharField(max_length=12)),
                ('marks', models.IntegerField(default=0)),
                ('isFirstTry', models.BooleanField(default=True)),
                ('isTimeOut', models.BooleanField(default=False)),
                ('startTime', models.DateTimeField(null=True)),
                ('tempTime', models.DateTimeField(null=True)),
                ('totalTime', models.IntegerField(default=-1)),
            ],
        ),
    ]
