# Generated by Django 4.1.7 on 2023-03-18 03:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_RC', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='totalTime',
            field=models.DurationField(default=datetime.timedelta(seconds=12600)),
        ),
    ]
