# Generated by Django 4.1.1 on 2023-03-10 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_RC', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 10, 19, 49, 17, 990966)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tempTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 10, 19, 49, 17, 990966)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_rank',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
