# Generated by Django 4.0.5 on 2023-05-04 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_RC', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatgptlifeline',
            name='lastUsed',
        ),
    ]
