# Generated by Django 4.1.7 on 2023-03-18 03:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_RC', '0002_alter_profile_totaltime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='totalTime',
            field=models.DurationField(default=datetime.timedelta(seconds=1800)),
        ),
    ]
