# Generated by Django 4.1.7 on 2023-03-12 06:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_RC', '0002_alter_profile_starttime_alter_profile_temptime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='remainingTime',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 12, 11, 40, 42, 734361)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tempTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 12, 11, 40, 42, 734361)),
        ),
    ]
