# Generated by Django 4.1.7 on 2023-03-23 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_RC', '0002_alter_profile_remainingtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lifeline2_status',
            field=models.BooleanField(default=False),
        ),
    ]
