# Generated by Django 4.0.5 on 2023-05-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_RC', '0002_remove_chatgptlifeline_lastused'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgptlifeline',
            name='lastUsed',
            field=models.FloatField(default=100.0),
        ),
    ]
