# Generated by Django 4.1.1 on 2023-02-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_RC', '0002_remove_profile_id_alter_profile_mob_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='curr_question',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mob_no',
            field=models.CharField(max_length=12),
        ),
    ]
