# Generated by Django 4.1.1 on 2023-02-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_RC', '0003_alter_profile_curr_question_alter_profile_mob_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='curr_question',
            field=models.IntegerField(default=1),
        ),
    ]
