# Generated by Django 4.0.5 on 2023-05-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_RC', '0003_chatgptlifeline_lastused'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgptlifeline',
            name='lastUsed',
            field=models.FloatField(default=1700000000.213593),
        ),
    ]
