# Generated by Django 4.1.7 on 2023-03-23 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_RC', '0003_profile_lifeline2_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lifeline2_checked',
            field=models.BooleanField(default=False),
        ),
    ]
