# Generated by Django 4.1.7 on 2023-03-18 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_RC', '0003_alter_profile_totaltime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='lifeline_1',
            new_name='simpleQuestionUsed',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='totalTime',
        ),
        migrations.AddField(
            model_name='profile',
            name='timeLLUsed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='remainingTime',
            field=models.DurationField(),
        ),
    ]
