# Generated by Django 4.1.1 on 2023-04-13 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_RC', '0004_profile_lifeline2_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='easyquestion',
            name='question_id',
            field=models.IntegerField(default=0),
        ),
    ]
