# Generated by Django 4.1.1 on 2023-03-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_RC', '0004_rename_lifeline_1_profile_simplequestionused_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lifeline1_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='lifeline1_status',
            field=models.IntegerField(default=0),
        ),
    ]
