# Generated by Django 4.0.5 on 2023-05-04 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_RC', '0004_profile_lifeline2_checked'),
    ]

    operations = [
        migrations.CreateModel(
            name='chatGPTLifeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=1000)),
                ('numUsed', models.IntegerField(default=0)),
                ('isDepleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='easyquestion',
            name='question_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='focuscount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='lifeline1_using',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='simpleQuestionUsed',
            field=models.BooleanField(null=True),
        ),
    ]
