# Generated by Django 4.0.5 on 2023-05-04 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_RC', '0005_chatgptlifeline_easyquestion_question_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='chatGPTLifeLine',
        ),
    ]
