# Generated by Django 4.1.1 on 2023-04-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_RC', '0005_easyquestion_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='simpleQuestionUsed',
            field=models.BooleanField(null=True),
        ),
    ]
