# Generated by Django 4.1.1 on 2023-03-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_RC', '0005_profile_lifeline1_active_profile_lifeline1_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='lifeline1_active',
        ),
        migrations.AddField(
            model_name='profile',
            name='lifeline1_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lifeline1_status',
            field=models.BooleanField(default=False),
        ),
    ]
