# Generated by Django 4.1.7 on 2023-02-23 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_RC', '0005_profile_answerresponses_profile_questionlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='questionList',
            new_name='questionIndexList',
        ),
    ]
