# Generated by Django 4.1.1 on 2023-04-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_RC', '0006_alter_profile_simplequestionused'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_response',
            name='isSimpleQuestion',
            field=models.BooleanField(null=True),
        ),
    ]
