# Generated by Django 4.1.1 on 2023-04-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_RC', '0007_alter_user_response_issimplequestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lifeline1_using',
            field=models.BooleanField(null=True),
        ),
    ]
