# Generated by Django 4.1.7 on 2023-02-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_RC', '0007_remove_profile_answerresponses'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='quesno',
            field=models.IntegerField(default=1),
        ),
    ]
