# Generated by Django 4.1.7 on 2023-02-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_RC', '0008_profile_quesno'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='marks',
            field=models.IntegerField(default=0),
        ),
    ]
