# Generated by Django 4.1.7 on 2023-02-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_RC', '0009_profile_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isFirstTry',
            field=models.BooleanField(default=True),
        ),
    ]
