# Generated by Django 4.1.1 on 2023-04-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_RC', '0009_alter_profile_lifeline1_using'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='lifeline1_using',
            field=models.BooleanField(null=True),
        ),
    ]
