# Generated by Django 4.1.1 on 2023-04-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_RC', '0010_alter_profile_lifeline1_using'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='focuscount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_response',
            name='isSimpleQuestion',
            field=models.BooleanField(default=False),
        ),
    ]
