# Generated by Django 4.1.1 on 2023-02-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_RC', '0010_profile_isfirsttry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='quesno',
            field=models.IntegerField(default=0),
        ),
    ]
