# Generated by Django 4.1.1 on 2023-02-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_RC', '0011_alter_profile_quesno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='quesno',
            field=models.IntegerField(default=1),
        ),
    ]
