# Generated by Django 4.1.1 on 2023-05-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_RC', '0011_profile_focuscount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='focuscount',
            field=models.IntegerField(default=3),
        ),
    ]
