# Generated by Django 4.1.1 on 2023-05-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_RC', '0012_alter_profile_focuscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='lifeline1_using',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='simpleQuestionUsed',
            field=models.BooleanField(default=True),
        ),
    ]
