# Generated by Django 4.1.7 on 2023-03-08 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_RC', '0012_alter_profile_quesno'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isTimeOut',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 8, 20, 8, 59, 696465)),
        ),
    ]
