# Generated by Django 4.1.7 on 2023-03-08 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_RC', '0013_profile_istimeout_profile_starttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tempTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 8, 20, 23, 20, 996232)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 8, 20, 23, 20, 996232)),
        ),
    ]
