# Generated by Django 4.1.1 on 2023-05-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_RC', '0013_alter_profile_lifeline1_using_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='lifeline1_using',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='simpleQuestionUsed',
            field=models.BooleanField(default=False),
        ),
    ]
