# Generated by Django 4.1.7 on 2023-03-08 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_RC', '0014_profile_temptime_alter_profile_starttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='totalTime',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 8, 20, 52, 15, 544262)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tempTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 8, 20, 52, 15, 544262)),
        ),
    ]
