# Generated by Django 4.1.7 on 2023-03-09 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_RC', '0015_profile_totaltime_alter_profile_starttime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 9, 17, 19, 19, 852380)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tempTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 9, 17, 19, 19, 852380)),
        ),
    ]
