# Generated by Django 4.0.5 on 2023-05-11 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_RC', '0020_profile_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cacheQuestion',
            field=models.IntegerField(default=-1),
        ),
    ]
