# Generated by Django 4.0.5 on 2023-05-11 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_RC', '0021_profile_cachequestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='cacheQuestion',
            new_name='cacheAnswer',
        ),
    ]
