# Generated by Django 4.1.1 on 2023-05-12 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_RC', '0027_profile_lifeline2_timeout_alter_profile_user_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='display_name',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
    ]
