# Generated by Django 4.1.1 on 2023-03-16 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp_RC', '0001_initial'),
        ('Question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_response',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp_RC.profile'),
        ),
    ]
