# Generated by Django 4.1.1 on 2023-03-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EasyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('easyquestion_no', models.IntegerField()),
                ('easyquestion', models.CharField(max_length=1000)),
                ('easyanswer', models.IntegerField(default=-1)),
            ],
        ),
    ]
