# Generated by Django 4.1.7 on 2023-02-23 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0002_remove_user_response_response_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_response',
            name='question_id',
        ),
    ]
