# Generated by Django 4.1.7 on 2023-02-23 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_RC', '0008_profile_quesno'),
        ('Question', '0003_remove_user_response_question_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_response',
            name='question_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp_RC.profile'),
        ),
    ]
