# Generated by Django 4.1.7 on 2023-03-18 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0004_user_response_issimplequestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='easyquestion',
            old_name='easyanswer',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='easyquestion',
            old_name='easyquestion',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='easyquestion',
            old_name='easyquestion_no',
            new_name='question_no',
        ),
    ]
