# Generated by Django 4.1.7 on 2023-02-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0004_user_response_question_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_response',
            old_name='question_id',
            new_name='user_profile',
        ),
        migrations.AddField(
            model_name='user_response',
            name='quetionID',
            field=models.IntegerField(default=-1),
        ),
    ]
