# Generated by Django 4.1.7 on 2023-02-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0005_rename_question_id_user_response_user_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.IntegerField(default=-1),
        ),
    ]
