# Generated by Django 4.1.1 on 2023-03-18 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0005_rename_easyanswer_easyquestion_answer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='easyquestion',
            old_name='answer',
            new_name='easyanswer',
        ),
        migrations.RenameField(
            model_name='easyquestion',
            old_name='question',
            new_name='easyquestion',
        ),
        migrations.RenameField(
            model_name='easyquestion',
            old_name='question_no',
            new_name='easyquestion_no',
        ),
    ]
