# Generated by Django 4.1.7 on 2023-03-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0006_alter_question_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_response',
            name='response1',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user_response',
            name='response2',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
